<?php
require_once('../includes/application_top.php');

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<LINK href="HELP.CSS" type=text/css rel=stylesheet>

<p class="welcome" align="center">Welcome to TheBursar®</p>
<table width="670" align="center" border="0" cellpadding="1" cellspacing="2">
  <tbody> 
  <tr> 
    <td colspan="5" height="67"> 
      <p>TheBursar®  MX is the easiest way to mantain, manage, and propell your school to the next level in a single, web-centric environment. 
        TheBursar MX provides the tools to make the running of your school fast and efficient. From managing revenue, to reporting on academic performances</p>
      
  </tr>
  <tr> 
    <td colspan="5" height="143"> 
      <blockquote> 
        <p><br>
          <span class="heading">Getting Started</span><br>
          Be sure to register to receive the latest information about upgrades 
          and new products, technical support, and more. Register <a href="http://www.macromedia.com/go/software_register">online</a> now, 
        </p>
        <p><a href="http://www.macromedia.com/go/fireworksmx_releasenotes" class="heading">Release 
          Notes</a><br>
          Release Notes contain the latest information and known issues about 
          TheBursar MX.<br>
        </p>
  
      </blockquote>
    </td>
  </tr>
  <tr> 
    <td width="400">&nbsp;</td>
    <td width="23">&nbsp;</td>
    <td width="350">&nbsp;</td>
    <td width="11">&nbsp;</td>
    <td width="190">&nbsp;</td>
  </tr>
  <tr valign="top"> 
    <td width="400" height="23"> 
      <div class="heading" align="left">TheBursar MX</div>
    </td>
    <td width="23" height="23">&nbsp;</td>
    <td width="350" height="23"> 
      <div class="heading" align="left">Technical Support</div>
    </td>
    <td width="11" height="23">&nbsp;</td>
    <td width="190" height="23" nowrap="nowrap"> 
      <div class="heading" align="left">Online Resources</div>
    </td>
  </tr>
  <tr> 
    <td colspan="5"> 
      <hr align="left" size="1">
    </td>
  </tr>
  <tr> 
    <td width="400"> 
      <div align="left"><a href="http://www.macromedia.com/go/fireworksmx_releasenotes">Release Notes</a></div>
    </td>
    <td width="23">&nbsp;</td>
    <td width="350" height="16"> 
      <div align="left"><a href="http://www.macromedia.com/go/fireworks_forum">Online 
        Forums</a></div>
    </td>
    <td width="11">&nbsp;</td>
    <td width="190" height="16" nowrap="nowrap"> 
     
    </td>
  </tr>
  <tr> 
    <td width="400" height="16"> 
      <div align="left"><a href="http://www.macromedia.com/go/fireworksmx_whatsnew">What's New in TheBursar 
        MX</a></div>
    </td>
    <td width="23">&nbsp;</td>
    <td width="350" height="14"><a href="http://www.macromedia.com/go/fireworks_support">Support Resources</a></td>
    <td width="11">&nbsp;</td>
    <td width="190" nowrap="nowrap"> 
      <div align="left"><a href="http://www.macromedia.com/go/fireworks_training">Training</a></div>
    </td>
  </tr>
  <tr> 
    <td width="400" height="11"> 
      <div align="left"><a href="file:///C:/Program%20Files/Macromedia/Fireworks%20MX/License.htm">End User License Agreement</a></div>
    </td>
    <td width="23" height="11">&nbsp;</td>
    <td width="350" height="11"><a href="http://www.macromedia.com/go/fireworks_requests">Enhancement Requests 
      and Bugs</a></td>
    <td width="11" height="11">&nbsp;</td>
    <td width="190" height="11" nowrap="nowrap"> 
      <div align="left"><a href="http://www.macromedia.com/go/fireworks_accessibility">Accessibility</a></div>
    </td>
  </tr>
  <tr> 
    <td width="400"> 
      <div align="left"><a href="http://www.macromedia.com/go/fireworks_cs">Customer Service</a></div>
    </td>
    <td width="23">&nbsp;</td>
    <td width="350" height="14">&nbsp;</td>
    <td width="11">&nbsp;</td>
    <td width="190" height="18" nowrap="nowrap"> 
     
    </td>
  </tr>
  
  <tr> 
    <td width="400" height="18"> 
      
    </td>
    <td width="23" height="18">&nbsp;</td>
    <td width="350" height="18">&nbsp;</td>
    <td width="11" height="18">&nbsp;</td>
    <td width="190" height="18" nowrap="nowrap">&nbsp;</td>
  </tr>
  <tr> 
    <td width="400">&nbsp;</td>
    <td width="23">&nbsp;</td>
    <td width="350">&nbsp;</td>
    <td width="11">&nbsp;</td>
    <td width="190" nowrap="nowrap">&nbsp;</td>
  </tr>
  
  <tr> 
    <td colspan="5">&nbsp;</td>
  </tr>
  <tr> 
    <td colspan="5" height="207"> 
      <div align="left"> 
        <p>Copyright © 2006-2012 Sync and its licensors. All 
          rights reserved. <a href="http://www.TheBursar.com/">www.TheBursar.com</a><br>
          <br>
          TheBursar, the TheBursar logo are trademarks or registered 
          trademarks of TheBursar in Uganda and/or other countries. 
          Other marks are the properties of their respective owners.<br>
          <br>
          Protected by one or more of Uganda. Patent patents pending. <br>
          <br>
          This computer program is protected by copyright law and international 
          treaties. Unauthorized reproduction or distribution of this program, 
          or any portion of it, may result in severe civil and criminal penalties, 
          and will be prosecuted to the maximum extent possible under the law. 
        
         </p>
      </div>
    </td>
  </tr>
  </tbody> 
</table>

</body></html>