<table border="0" width="100%" cellspacing="0" cellpadding="0"> 
  <tr>
    <td  colspan="2"  align="center">
    <span style='margin:0;padding:0;'><img src='images/sync.jpg' border="0"></span>
  <span style="color:#000000;font-size:11px;margin:0px;" ><br>Technology for Human beings<br>Email: <a href="mailto:katended@gmail.com">katended@gmail.com</a> Tel: +256 773397960</span></td>
  </tr>
</table>
